### ISSUE TITLE
HTML Color

### ISSUE THREAD

**Issue by brunoracosta** [trongthanh/vscode-boxythemekit#3]
I am working with Angular 2.

I detected a problem in the Boxy yesterday HTML colors. When I write "&&" the color is white but the background is also white. So It appears be nothing.

![error](https://cloud.githubusercontent.com/assets/2483403/25318109/c4cab416-285d-11e7-92bd-e3f14d1786f1.jpg)

**Comment by zhuowenli** [comment]
![jietu20170428-114700](https://cloud.githubusercontent.com/assets/9620783/25513578/a1d5fee4-2c08-11e7-88ea-395f3f43e803.jpg)

+1 in php

**Comment by trongthanh** [comment]
The background color is not applying. I'm looking into the issue.

**Comment by trongthanh** [comment]
Fixed in 0.0.5. 

I've just swapped the background color to use as foreground for invalid characters, while waiting for this issue from VSCode to settle https://github.com/Microsoft/vscode/issues/3429
