### ISSUE TITLE
Incorrect hightliting

### ISSUE THREAD

**Issue by brentluna** [trongthanh/vscode-boxythemekit#4]
When putting some code below a "content_for :javascripts" block, even though the code is outside the blocks scope, it seems to affect the highlighting. If I comment out the content_for block, the highlighting shows as expected. 
![screen shot 2017-05-23 at 10 37 57 am](https://cloud.githubusercontent.com/assets/7967287/26367701/4c46e8a8-3fa4-11e7-9147-e99dbff9ec66.png)
![screen shot 2017-05-23 at 10 37 42 am](https://cloud.githubusercontent.com/assets/7967287/26367702/4c48234e-3fa4-11e7-85a5-f0940a68f514.png)

**Comment by trongthanh** [comment]
Hi, what language is that? 

Besides, the highlight scope is controlled by VSCode. Have you checked if the same issue happens to default theme as well? If so, may be an issue should be posted to VSCode team.

**Comment by brentluna** [comment]
It's haml, just a stripped down html syntax.

You are correct, it seems to be a constant thing for all themes. Thanks!
