### ISSUE TITLE
Wrong Highlighting in PHP

### ISSUE THREAD

**Issue by Helfull** [trongthanh/vscode-boxythemekit#5]
![image](https://user-images.githubusercontent.com/720645/30794551-1d0be2fa-a1c9-11e7-9dde-969548075aa1.png)
Left sublime right vscode

notice the TypeHints and the `\DB::` they should be the same color as the use declarations

**Comment by trongthanh** [comment]
I did not have time to look at this issue and overlooked it for quite some time. 😅 Do you still use the theme and need the theme to support this? If not, I'll close this issue for now
